### ISSUE TITLE
请问为什么.el-upload-list__item的draggable属性是false，导致无法拖拽

### ISSUE THREAD

**Issue by luoxiaominga** [natee/el-upload-sortable#4]

**Comment by luoxiaominga** [comment]
![1602493517(1)](https://user-images.githubusercontent.com/41247210/95727734-2dab2b00-0cad-11eb-9a2d-c9a3c06e9e21.png)

**Comment by natee** [comment]
@luoxiaominga  参看 [vuedraggable](https://david-desmaisons.github.io/draggable-example/)

这个不是导致无法拖拽的原因

**Comment by luoxiaominga** [comment]
> @luoxiaominga 参看 [vuedraggable](https://david-desmaisons.github.io/draggable-example/)
> 
> 这个不是导致无法拖拽的原因

你好 我安装了vuedraggable之后还是老样子呢。 拖动过程中鼠标按着不放图片的视图与数据的确可以更换顺序，可是一旦放开鼠标就又回到原来的地方呢 哪怕直接应用您源码中的demo也一样这种情况

**Comment by natee** [comment]
先尝试vuedraggable 插件的demo 有没有问题

**（必填）请填写问题描述或截图：**
？

**（必填）请填在线链接：**
？

**（必填）请填写期望的结果：**
？

**（必填）请填写以下信息：**

- OS: ？
- Browser: ？
- vue: ？

**Comment by luoxiaominga** [comment]
> 先尝试vuedraggable 插件的demo 有没有问题
> 
> **（必填）请填写问题描述或截图：**
> ？
> 
> **（必填）请填在线链接：**
> ？
> 
> **（必填）请填写期望的结果：**
> ？
> 
> **（必填）请填写以下信息：**
> 
> * OS: ？
> * Browser: ？
> * vue: ？
你好我发现是demo中没有在picUpdate更新list重新传递到子组件所致的 。故子组件中的props的list一直没有更新。改成这样子便可以了
![1602575497(1)](https://user-images.githubusercontent.com/41247210/95831984-50504900-0d6c-11eb-8a3c-f53847f2027d.png)

**Comment by natee** [comment]
当提供一个默认列表时该方法可行，但不提供默认 `list` 参数时会有排序不生效的 bug ，#5 已修复该问题
